### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#2]
I need to add a logger for getting more details when something don't work as expected, but without loading the console.

**Comment by baruchiro** [comment]
OK, I'm using the [electron-log](https://www.npmjs.com/package/electron-log) logger, but it prints only to the shell, and not to the Dev-Console.
According to [this issue](https://github.com/megahertz/electron-log/issues/27#issuecomment-561701856), it should support to print to the Dev-Console.

Maybe we need to upgrade some packages.

**Comment by Arielgordon123** [comment]
I think that now there are logs on the Dev-Console

**Comment by baruchiro** [comment]
One more thing, sometimes there is an error printed to the Dev-Console that not printed to the file.

There is an option to reassign the `console.log` and `console.error` to use `electron-log`, but the `console.log` assignment leads to strange log (something like `date > date with some ticks later > date with some ticks later > ... > The log`), so at least we can assign the `console.error`, although I think it should be already implemented by the error configurations in `electron-log`.

**Comment by baruchiro** [comment]
And what about logging in `modules`?
Maybe we need to define a global logger and use it when we want, without injecting it to each method?

**Comment by baruchiro** [comment]
Reopen from #101

**Comment by baruchiro** [comment]
closed by https://github.com/brafdlog/budget-tracking/issues/141
