### ISSUE TITLE
Use yarn instead on npm in README

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#25]
[As @esakal said](https://github.com/eshaham/israeli-bank-scrapers/issues/269#issuecomment-568179319), We use `yarn` as the package manager, but in the README I wrote `npm` commands.

To solve this issue, need to clone a fresh clone, and see which `yarn` commands we need to run until we run the `dev`, `test` and `build:repease`, and write these commands in the README.

The commands can also be taken from the CI (`yml`) files.

**Comment by danishsshaikh** [comment]
is this issue to change the remove the npm and use yarn commands instead?

**Comment by baruchiro** [comment]
Hi @danishsshaikh , I updated the issue description
