### ISSUE TITLE
Replace the vuex-electron plugin

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#30]
The [`vuex-electron`](https://github.com/vue-electron/vuex-electron/issues/44) package is not under maintaining anymore.

In this app, we need more attention about persisting the `vuex` state, because we have to keep the sensitive data (passwords, keys) out of the persistent file (unless we keeping the whole persistent safe).

So this issue requires looking for **maintained**, **customizable** and **secured** `Vuex` plugin, or developing our own plugin.

**Comment by baruchiro** [comment]
Alternatives:

- [`electron-store`](https://github.com/sindresorhus/electron-store)
- [`vuex-persistedstate`](https://github.com/robinvdvleuten/vuex-persistedstate) with [custom storage](https://github.com/robinvdvleuten/vuex-persistedstate#customize-storage)

**Comment by Arielgordon123** [comment]
the [`vuex-persistedstate`](https://github.com/robinvdvleuten/vuex-persistedstate) package saves and read from the local storage by default, so it is easier to integrate it into our app.

the[`electron-store`](https://github.com/sindresorhus/electron-store) lets you store JSON Objects to file so the data will be saved to disk but then you need to update the vuex store on every change.

there is an advantage to `electron-store` like mentioned [`here`](https://github.com/sindresorhus/electron-store/issues/17#issuecomment-307561288)

local storage is limited to 10MB vs 4096 bytes on cookies.

**Comment by baruchiro** [comment]
**vuex-persistedstate:**
I'm not sure we can use `local storage` in Electron, and I'm not sure it will save the state between sessions.
But `vuex-persistedstate` support [custom source](https://github.com/robinvdvleuten/vuex-persistedstate#customize-storage), so we can use something even better then save and load the whole db file for each time the store changes.

And I just realized how it works!

The `vuex-persistedstate` uses `local storage` to save the `vuex` state.
And the `electron-store` implement the `local storage` interface, for saving in the filesystem.

So it seems obvious, we need to use `vuex-persistedstate` with `electron-store` as custom storage.

But keep it in mind, maybe it is overkill.

**Comment by baruchiro** [comment]
Closed, replaced in https://github.com/brafdlog/budget-tracking
