### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by OHeimlich** [baruchiro/israeli-bank-scrapers-desktop#38]

**Comment by Arielgordon123** [comment]
if you want to build from source code you can do it as described here
https://github.com/baruchiro/israeli-bank-scrapers-desktop#build-setup

or you can download the app from here
(choose the .exe file if you are using windows)
https://github.com/baruchiro/israeli-bank-scrapers-desktop/releases

**Comment by baruchiro** [comment]
@OHeimlich Thanks for the question!

Can you tell which operating system you are running (Windows, Linux or OSX)?

Are you experiencing any problems running the software?

**Comment by OHeimlich** [comment]
Sure, seems like a great project.
I'm working over Linux (Ubuntu)
but this is what i;m getting while trying to build from src:

```
ori@ori-pc:~/Downloads/israeli-bank-scrapers-desktop$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
```

**Comment by baruchiro** [comment]
I'm not sure you are using the right `yarn`..

See [this comment](https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365)
