### ISSUE TITLE
node-keytar fail on Linux

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#43]
from @Arielgordon123 :
![WhatsApp Image 2020-01-05 at 18 19 43](https://user-images.githubusercontent.com/17686879/71784467-73d7ad80-2ffc-11ea-8bc5-13160395f063.jpeg)

See this [bug](https://github.com/atom/node-keytar/issues/132). What is the `gnome-keyring`?

- [ ] Solve the bug.
- [ ] Write a test for saving a password with `keytar` **in CI only**.

**Comment by baruchiro** [comment]
@Arielgordon123 In my Ubuntu machine it is not reproduced.
Can you verify it?

**Comment by Arielgordon123** [comment]
I've checked on kali Linux and It's worked for me too
