### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by yaelgreen** [baruchiro/israeli-bank-scrapers-desktop#64]
When I try to Export to Google Spreadsheet I get this error (it's shown when I hover over the small red X to the right of "Export to Google Spreadsheet" ):
Cannot read property '0' of null

and the log shows:
>┏ Electron -------------------
>
>  14:34:03.076 › TypeError {}
>  
>┗ ----------------------------

**Comment by baruchiro** [comment]
Thank you for contributing!

- Did you follow the [sharing instructions](https://github.com/baruchiro/israeli-bank-scrapers-desktop/blob/master/docs/share-spreadsheet.md)?
- Can you share the sharing link to the document with us?

**Comment by baruchiro** [comment]
I'm just working on (#9 ) replacing the authenticarion process with Google so I believe it will be resolved.

**Comment by Arielgordon123** [comment]
I think that this error comes from the regex in this line
https://github.com/baruchiro/israeli-bank-scrapers-desktop/blob/a67068cf45e015637bc4c92915d208ed405940d4/src/renderer/modules/spreadsheet.js#L80
sometimes there is no `-` at all or there is but not in this particular place.

anyway, I think that @baruchiro working to replace this workflow.
