### ISSUE TITLE
Wrong year 

### ISSUE THREAD

**Issue by yaelgreen** [baruchiro/israeli-bank-scrapers-desktop#65]
When I click "import" with "show browser" on I see it scrapes data from 10/01/19 - 10/01/2020.
Once the import is done I see all the data from the sheet are in the range 31/12/20 - 02/01/2020.
of course the dates are wrong since today is 10/01/2020.
I looked at the content of the cells and reached the conclusion it shows all the 2019 dates as 2020.

**Comment by baruchiro** [comment]
Hi, @yaelgreen, sorry for the delay, I was busy with some broad tasks that would make it easier for us to fix bugs later.

I can't reproduce your bug, I tried to import from _Bank Leumi_, _Mozrahi Bank_ and _Leumi Card (Max)_, and still, all the transactions in the table are from **01/02/19** to **10/02/2020** (pending).

@Arielgordon123, Have you seen something like this?

**Comment by Arielgordon123** [comment]
I didn't see anything like that
but I also checked Leumi Card(Max) and Bank Leumi

**Comment by baruchiro** [comment]
Closed.

@yaelgreen Please open if this bug continued in the latest version, and try to add more details.
