### ISSUE TITLE
Prerequisites and developer workspace

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#73]
In README, we need to add an explanation how to init a developer workspace:

- [x] Install `node` (version?)
- [x] Install `Yarn`
- [x] Project structure
- [ ] Trubleshooting

**Comment by baruchiro** [comment]
@Arielgordon123 What is the lowest version of `node` we support?

**Comment by barakbitan** [comment]
Precondition for installation:
nodeJS at lest 8.16.0v or higher  (https://nodejs.org/en/)
install yarn in project files  (https://yarnpkg.com/en/docs/install#windows-stable)
You need to install the latest version of Python

**Comment by baruchiro** [comment]
- [Yarn](https://classic.yarnpkg.com) (classic)
- [NodeJS](https://nodejs.org/) version 10.13.0

@barakbitan I tried to create a dev workspace in the Windows **Sandbox** app, and I had to install only these prerequisites. Maybe it because you tried before the #66 is merged.
