### ISSUE TITLE
[DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#80]
`src/service/encryption/crypto.js` prints this message as `error` in the renderer console:
> [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.

**Comment by baruchiro** [comment]
> Warning: Use Cipheriv for counter mode of aes-256-ctr

**Comment by Arielgordon123** [comment]
so now in order to encrypt or decrypt something we need to save also the initialization vector

@baruchiro do you think that it is a good idea to save this in the keytar with the key?

**Comment by baruchiro** [comment]
Can you explain what is the initialization vector and why do you think this is the solution?

I thought the problem is just in a deprecated method.

**Comment by Arielgordon123** [comment]
[Initialization vector](https://en.wikipedia.org/wiki/Initialization_vector)

the methods `crypto.createCipher` and `crypto.createDecipher` are deprecated 
as the warning itself said you should use `crypto.createCipheriv` and `crypto.createDecipheriv`

**Comment by baruchiro** [comment]
Closing, the project moved to https://github.com/brafdlog/budget-tracking
