### ISSUE TITLE
Moving from ElementUI to Vuetify

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#98]
This is a general issue for syncing the work of porting our components to `Vuetify`.
The design issue is #49 and all the other issues marked as [UI/UX](https://github.com/baruchiro/israeli-bank-scrapers-desktop/labels/UI%2FUX).

@Arielgordon123 The PR #97 is waiting for your approval.

After this PR merges, we will be able to continue port the components to `Vuetify`.
Like I said before, I don't see it as a high priority other than a few specific components:

- [x] `DataTable` (https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/110)
- [x] `App` and `MainPage` (https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/110)
- [x] `Importers` & `Exporters` (https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/111, https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/119, https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/140)
- [x] `footer` (https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/113)

We need to keep in sync between us, so that if someone chooses to port a particular component, someone else will not work on the same task.
That is why we should try to update here on who is working on what.

**Comment by baruchiro** [comment]
I'm starting to work on the `App` and `MainPage`, because I think we need to redesign them before applying the changes in the `DataTable`.

**Comment by baruchiro** [comment]
Since I already have an implementation of Vuetify `DataTable`, I will push it after the #100 merge

**Comment by baruchiro** [comment]
I'm working on the `footer` now

**Comment by Arielgordon123** [comment]
I will start with the Importers & Exporters

**Comment by Arielgordon123** [comment]
I've done with the Importer in PR #119 
now I will start to work on the Exporter
