### ISSUE TITLE
Remote error from secret service

### ISSUE THREAD

**Issue by Arielgordon123** [baruchiro/israeli-bank-scrapers-desktop#99]
I've tried to run the app from snap on clean ubuntu 18.04 machine and I am getting this error

`** Message: 22:07:13.078: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.79" (uid=1000 pid=1944 comm="/snap/israeli-bank-scrapers-desktop/51/israeli-ban" label="snap.israeli-bank-scrapers-desktop.israeli-bank-scrapers-desktop (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.20" (uid=1000 pid=1102 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")`

maybe this issue related to  #14?

anyway, it seems like the solution is to config `snapcraft.yaml` properly 

- [ ] use `snapcraft.yaml` template could found [here](https://github.com/snapcrafters/fork-and-rename-me/blob/master/snap/snapcraft.yaml) 
- [ ] add [password-manager-service](https://snapcraft.io/docs/password-manager-service-interface)
- [ ] Update `snapcraft.yaml` on CI / Release Pipeline?

**Comment by Arielgordon123** [comment]
This error only accord's when installing from the snap
 the .deb works well

**Comment by baruchiro** [comment]
Remember we talked about replacing the `keytar` with encrypting a user password, I think it was about #30 . `keytar` causes us a lot of problems, so I suggest we don't spend too much time solving the problems, when we can spend the same time developing a new solution.

**Comment by baruchiro** [comment]
Referenced here: https://github.com/brafdlog/budget-tracking/issues/131#issuecomment-748971385
